stages:
  - stage: Build
    displayName: Build Stage
    jobs:
      - job : BuildJob
        displayName: Build Job 1    
        pool:
          vmImage: 'Ubuntu-16.04'
        steps:
        - task: NodeTool@0
          inputs:
            versionSpec: '10.x'
        - script: |
            npm install -g @angular/cli
            npm install
            ng build --prod
          displayName: 'npm install and build'
        - script: |
           npm pack
          displayName: 'Package for npm release'

        - task: CopyFiles@2
          inputs:
            sourceFolder: '$(Build.SourcesDirectory)'
            contents: '*.tgz' 
            targetFolder: $(Build.ArtifactStagingDirectory)/build
          displayName: 'Copy npm package'
        - script: echo $(Build.ArtifactStagingDirectory) | echo hello 
        - task: CopyFiles@2
          inputs:
            sourceFolder: '$(Build.SourcesDirectory)'
            contents: 'package.json' 
            targetFolder: $(Build.ArtifactStagingDirectory)/build
          displayName: 'Copy package.json'
        - task: ArchiveFiles@2
          displayName: 'Archive files'
          inputs:
            rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
            includeRootFolder: false
            archiveType: zip
            archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
            replaceExistingArchive: true
        - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
          artifact: drop
        - task: ArchiveFiles@2
          inputs:
            rootFolderOrFile: '$(Build.BinariesDirectory)'
            includeRootFolder: true
            archiveType: 'zip'
            archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
            replaceExistingArchive: true
        - task: PublishBuildArtifacts@1
          inputs:
            pathtoPublish: '$(Build.ArtifactStagingDirectory)/build'
            artifactName: npm2
          displayName: 'Publish npm artifact'

  - stage: Test
    displayName: Test Stage
    jobs:
      - job: TestJob
        displayName: Test Job 1
        steps:
          - script: echo TestPipeline
          
  - stage: Deploy
    displayName: Deploy Stage
    jobs:
      - job: DeployJob
        displayName: Deploy Job 1
        steps:
          - script: echo DeployJob