

stages:
  - stage: Build
    displayName: Build Stage
    jobs:
      - job : BuildJob
        displayName: Build Job 1    
        pool:
          vmImage: 'Ubuntu-16.04'
        steps:
        - task: NodeTool@0
          inputs:
            versionSpec: '10.x'
        - script: |
            npm install -g @angular/cli
            npm install
            ng build --prod
          displayName: 'npm install and build'
        - script: |
           npm pack
          displayName: 'Package for npm release'

        - task: ArchiveFiles@2
          displayName: 'Archive files'
          inputs:
            rootFolderOrFile: '$(System.DefaultWorkingDirectory)/dist'
            includeRootFolder: false
            archiveType: zip
            archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
            replaceExistingArchive: true
        - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
          artifact: drop
